[workspace]

members = [
    "echo_server",
    "echo_client",
    "traffic_light",
    "calculate_sum",
    "calculate_area",
    "code_wars",
    "from_mvp",
    "hello_macro",
    "hello_macro_derive",
    "pancakes",
    "hello",
    "demos",
    "scrape_url",
    "httpie",
    "thumbor",
]